services:
  spark-connect:
    image: apache/spark:3.5.3
    command:
      - "/opt/spark/sbin/start-connect-server.sh"
      - "--packages"
      - "org.apache.spark:spark-connect_2.12:3.5.3"
      - "--conf"
      - "spark.driver.host=0.0.0.0"
    ports:
      - "15002:15002"
